// DOM Selection
const input = document.getElementById("hangman-letter-guess")
input.addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
      event.preventDefault();
      document.getElementById("hangman-letter-submit").click();
    }
});
const wordContainer = document.getElementById("hangman-word-container");
const hangman = document.getElementById("hangman-hangman")
const hangmanWrongGuesses = document.getElementById("hangman-wrong-guesses")

const isCharacter = (string) => {
    return string.toUpperCase() != string.toLowerCase();
}

// GAME
class GameState {
    constructor(word) {
        word = word.toUpperCase();
        this.word = word;
        this.incorrectGuesses = 0;
        this.guessedLetters = new Set();
        this.correctLetters = new Array(word.length).fill(false);
        this.state = "guessing";

        for (let i = 0; i < this.word.length; i++) {
            if (!isCharacter(this.word[i])) {
                this.correctLetters[i] = true;
            }
        }
    };

    displayWord = () => {
        let letters = new Array();
        
        for (let i = 0; i < this.word.length; i++) {
            let span = document.createElement("span");
            span.className = "letter";
            if (this.correctLetters[i]) {
                span.textContent = this.word[i];
            }
            else {
                span.textContent = "_";
            }
            letters.push(span);
        }
        
        wordContainer.replaceChildren(...letters);
    }

    displayHangman = () => {
        hangman.textContent = `Total guesses: ${this.guessedLetters.size}, Incorrect: ${this.incorrectGuesses}`;
    }

    displayWrongLetter = (guess) => {
        let letter = document.createElement("span");
        letter.className = "letter";
        letter.textContent = guess;
    
        hangmanWrongGuesses.appendChild(letter);
    }

    incorrectGuess = (guess) => {
        this.incorrectGuesses++;

        this.displayWrongLetter(guess);
    }

    isGameOver = () => {
        if (this.incorrectGuesses >= 10) {
            this.state = "lost";
            return true;
        }
        if (this.correctLetters.every((val, i, arr) => val === true)) {
            this.state = "won";
            return true;
        }
        return false;
    }

    guessLetter = () => {
        let guess = input.value;
        // clear input field
        input.value = null;
    
        if (guess === undefined || guess === "") {
            // javascript moment
            return;
        }

        if (guess.toUpperCase() == guess.toLowerCase()) {
            // Not a letter (mostly...)
            return;
        }
        guess = guess.toUpperCase();
    
        if (this.guessedLetters.has(guess)) {
            // already guessed
            return;
        }
        
        this.guessedLetters.add(guess);

        let positions = new Array();
        for (let i = 0; i < this.word.length; i++) {
            if (this.word.charAt(i) == guess) {
                positions.push(i);
            }
        }
    
        if (positions.length === 0) {
            this.incorrectGuess(guess);
        }
    
        for (let i = 0; i < positions.length; i++) {
            this.correctLetters[positions[i]] = true;
        }

        this.displayWord();
        this.displayHangman();

        if (this.isGameOver()) {
            if (this.state === "won") hangman.textContent = "YAY YOU WON GOOD JOB I'M IMPRESSED!";
            else hangman.textContent = `WOW YOU'RE SO BAD I'M IMPRESSED! THE WORD WAS ${this.word}`;
        }
    }
}

const words = [
    "ABSORB", "ADDE", "ADMETE", "AGAM", "AGEN", "AINA", "AKTAD", "AKURUM/RATIONELL", "AKURUM", "AKUT", "ALÄNG", "ALESKÄR", "ALEX", "ALGOT", "ALHEDE", "ALINAa", "ALKALISK", "ALLDAGLIG", "ALMSTED", "ALOE VERA", "ALRIK", "ALSEDA", "ALSLEV", "ALVINE PÄRLA", "ALVINE", "ALVINE SPETS", "ALVINE STRÅ", "AMMERÖ", "ANEBODA", "ANGENÄM", "ANNONS", "ANNO SANELA", "ANNO TUPPLUR", "ANNVY", "ANSLUTA", "ANTAGEN", "ANTHURIUM", "ANTIFONI", "ANTILOP", "ANTONIUS", "APA", "APTITLIG", "ARHOLMA", "ARÖD", "ARVIKA", "ARV", "ASKHOLMEN", "ASPEKT", "ATLANT", "ATTEST", "AVSKILD", "ÅDERBLAD", "ÅDUM", "ÅFJÄRDEN", "ÅKERBY", "ÅKERGYLLEN", "ÅKERKULLA", "ÅKERMADD", "ÅKERVALLMO", "ÅRSTID", "ÅSELE", "ÅSIKT", "ÅSTORP", "ÅSUNDA LED", "ÅSUNDEN", "ÅTRÅVÄRD", "ÄDELSTEN", "ÄLGHULT", "ÄLGÖRT", "ÄLMSTA", "ÄNDLIG", "ÄNGSFLY", "ÄNGSKRASSE", "ÄNGSÖ", "ÄNGSSKÄRA", "ÄNGSSPIRA", "ÄPPELVINÄGER MED LINGON", "ÄPPLARÖ", "ÄTRAN", "BACKABRO", "BADET", "BAGGÖN", "BAGIS", "BAKELSE PRINSESS", "BANDSJÖN", "BÄRBAR", "BAREN", "BARNSLIG", "BAROMETER", "BARSK", "BASISK", "BASNÄS", "BASTIG", "BÄSTIS", "BEAUCARNEA RECURVATA", "BEBOELIG", "BEDÅRANDE", "BEDDINGE LÖVÅS", "BEDDINGE", "BEFRIANDE", "BEHANDLA", "BEKKESTUA", "BEKVÄM", "BENNO", "BENZY", "BERIT", "BERLEVÅG", "BERNHARD", "BERTA RUTA", "BERTIL", "BESÖKA", "BESTÅ/FRAMSTÅ/INREDA", "BESTÅ BURS", "BESTÅ BURS TV", "BESTÅ", "BESTÅENDE", "BESTÅ TV", "BETEENDE", "BETRAKTA", "BETRODD", "BETYDLIG", "BEVARA", "BEVISTA", "BIGARRÅ", "BILD", "BILLINGEN", "BILLSTA", "BILLY/BENNO TV", "BILLY/BILLY VALBO", "BILLY", "BIRKELAND", "BISPGÅRDEN", "BISSA", "BISTÅ", "BJÄLBO", "BJÄRNUM", "BJÖRKUDDEN", "BJÖRNBÄR", "BJÖRNLOKA", "BJÖRNLOKA FIGUR", "BJURSTA/BERNHARD", "BJURSTA/BÖRJE", "BJURSTA/HENRIKSDAL", "BJURSTA/IDOLF", "BJURSTA/NILS", "BJURSTA/PREBEN", "BJURSTA/TERJE", "BJURSTA/VILMAR", "BJURSTA", "BLADET", "BLADIS", "BLÅMES", "BLANDA", "BLANKETT", "BLASKA", "BLÅST", "BLÅVINGE", "BLECKA", "BLEKVIVA", "BLIXT", "BLOMSTER", "BOHOLMEN", "BÖJA", "BOJNE", "BOKSEL", "BOLLKAKTUS", "BOLMEN", "BOMULL", "BONDIS", "BORGHILD", "BORGSJÖ", "BORGSJÖ TV", "BÖRJA", "BÖRJE", "BORRBY", "BORRIS", "BOSNÄS", "BOSSE", "BOTKYRKA", "BRÄDA", "BRALLIS", "BRAMSÖN/FLISÖ", "BRAMSÖN", "BRANÄS", "BRÅN", "BRÅVIKEN", "BRAVUR", "BREDGRUND", "BREDSKÄR", "BREIM", "BRIMNES", "BRITTEN NUMMER", "BRÖDHULT", "BRÖDMIX FLERKORN", "BRÖD MJUKKAKA", "BRÖD TUNNBRÖD", "BROMMÖ", "BROMÖLLA", "BRUMBJÖRN", "BRUMMA", "BRUNKRISSLA", "BRUSALI", "BRYGGKAFFE MELLANROST", "BRYGGKAFFE MÖRKROST", "BRYNE", "BUDSKÄR", "BUMERANG", "BURKEN", "BUSA", "BUSUNGE", "BYÅS TV", "BYGEL", "BYGLAND", "BYHOLMA/MARIEBERG", "BYHOLMA", "BYIG", "BYLLAN", "CACTACEAE", "CAJA", "CALYPSO", "CAPITA", "CASHEWNÖT", "CENTIGRAD LED", "CHAMAEDOREA ELEGANS", "CHOKLADKROKANT BREDBAR", "CHOKLAD LINGON", "CHOKLAD LJUS", "CHOKLAD MÖRK", "CHOKLAD NÖT", "CHOSIGT", "CHRYSALIDOCARPUS LUTESCENS", "CILLA", "CIRKUSTÄLT", "CRASSULA", "CYLINDER", "DALFRED", "DALSKÄR", "DÄNKA", "DANNSKÄR", "DANSA", "DANSBO", "DÅTID", "DEGERÖN", "DEKAD", "DESSERT", "DETOLF", "DIGNITET", "DILLING", "DIMMA", "DIMPA", "DINERA", "DIODER LED", "DIOD", "DIREKT", "DITO", "DITTE", "DJUPVIK", "DOCKSTA/ELMER", "DOCKSTA/IKEA PS", "DOCKSTA/TOBIAS", "DOCKSTA", "DOFTA", "DOKUMENT", "DOLD", "DOMBÅS", "DOMSJÖ", "DRACAENA MARGINATA", "DRACAENA MASSANGEANA", "DRACAENA", "DRAGAN", "DRAGGAN", "DRAGON", "DRAGÖR", "DRÄLLA", "DRÖMLIK", "DRÖMMAR", "DRÖNA", "DROPPAR", "DROPS", "DRUVFLÄDER", "DRUVMÅLLA", "DRYCK BLÅBÄR", "DRYCK BUBBEL ÄPPLE", "DRYCK BUBBEL PÄRON", "DRYCK FLÄDER", "DRYCK LINGON", "DRYCK NYPON", "DUDERÖ", "DUKEN", "DUKTIG", "DVALA", "DVÄRGPALM", "DYNING", "EDEBOVIKEN", "EDSVIK", "EGGEGRUND", "EIVOR", "EKARP", "EKÅS", "EKBY JÄRPEN/EKBY BJÄRNUM", "EKBY JÄRPEN/EKBY GÄLLÖ", "EKBY JÄRPEN/EKBY OXIE", "EKBY JÄRPEN/EKBY RISET", "EKBY JÄRPEN/EKBY STÖDIS", "EKBY JÄRPEN/EKBY TÖRE", "EKBY KARL/EKBY STÖDIS", "EKBY ÖSTEN/EKBY OXIE", "EKBY ÖSTEN/EKBY VALTER", "EKBY", "EKBY VIKTOR/EKBY RISET", "EKEBODA", "EKENÄS", "EKERÖ", "EKETÅNGA", "EKNE", "EKOLLON", "EKORRE", "EKTORP", "EKVIKEN", "ELDIG", "ELDSHULT", "ELLY", "ELMER", "ELSABO", "ELSEBET", "ELVERDAM", "ELVILDA", "EMMIE BLOM", "EMMIE", "EMMIE RAND", "EMMIE ROS", "EMMIE RUTA", "EMSEN", "ENERGISK", "ENFALDIG", "ENHOLMEN", "ENJE", "ENSEN", "ENSIDIG", "ENSKILD", "ENUDDEN ", "ENUDDEN", "ENVIS", "ERBIUM", "ERIK", "ERIKSLUND", "ERLAND", "ERSÄTTA", "ESBJÖRN", "ESPRESSOKAFFE", "ETTY", "EVALENA", "EVALILL", "EVALOTTA", "EVENTUELL", "EXPEDIT", "FABIAN", "FABLER", "FABLER BJÖRN", "FABRIKÖR", "FABRINA", "FABULÖS", "FADO", "FÅGELSTA", "FÅGLAVIK", "FÅGLEBODA", "FALSTER", "FAMNIG HJÄRTA", "FÅNIGT", "FANTASIRIK", "FANTASTISK", "FANTAST", "FÄRGGLAD", "FÄRGKULLA", "FÄRGLAV", "FÄRGRIK", "FAS", "FASTBO", "FAVORIT", "FEJAN", "FEJKA", "FENOMEN", "FERLE", "FESTLIGHET", "FICUS LYRATA", "FICUS MICROCARPA GINSENG", "FILLSTA", "FILUR", "FINFIN LED", "FINGAL", "FINKORNIG", "FINLIR", "FINNTORP/DJUPVIK", "FINNTORP", "FINTORP", "FISKÖ", "FIXA", "FJÄDERMOLN", "FJÄDRAR", "FJÄLKINGE", "FJÄLLBERGET", "FJÄLLJUNG", "FJÄLLSTA", "FJÄLLTRAV", "FJÄRDGRUND", "FJELLSE", "FLÄCKIG", "FLÄRDFULL", "FLAXA", "FLAXIG", "FLEST", "FLISÖ", "FLORERA", "FLÖRT", "FLUNDRA", "FLYGTUR", "FLYN LILL", "FLYTANDE", "FLYT", "FLYTTA", "FNISS", "FNITTER", "FOLLDAL", "FÖRÄNDRAD", "FÖREBILD", "FÖRHÖJA", "FORMAT", "FÖRNUFT", "FORSÅ", "FÖRSIKTIG", "FORSLA", "FÖRSÖKA", "FÖRSTÅELIG", "FÖRTJUST", "FÖRTROLIG", "FÖRVÄNTAD", "FÖRVAR", "FOTBLAD", "FOTO", "FRÄCK", "FRÄJEN", "FRAKTA", "FRAMTID", "FRANKLIN", "FRASERA", "FREDDE", "FREDLÖS", "FREDRIKA", "FRIDFULL", "FRIHETEN", "FRODE", "FRODIG", "FROST", "FRYEBO LED", "FRYKEN", "FUGA", "FULLEN", "FUSION", "FYLLEN", "FYLLIG", "FYNDIG", "FYRFALDIG", "FYRKANTIG", "GALANT", "GALEJ", "GÄLL", "GARDENIA JASMINOIDES", "GARNITYR", "GÅRÖ/DYNING", "GÅRÖ/RISÖ", "GÅRÖ", "GARPEN", "GÅSER", "GÅSGRUND", "GÄSPA", "GAVIK", "GEMAK", "GLÄDJANDE", "GLADSAX", "GLANSIG", "GLANSNÄVA", "GLÄNTA", "GLENN", "GLES", "GLIMMA", "GLIS", "GLITTRAN", "GLITTRAR", "GLIVARP/PREBEN", "GLIVARP/TOBIAS", "GLIVARP/VILMAR", "GLIVARP", "GNARP", "GODIS CHOKLADKROKANT", "GODIS FRUKT", "GODIS", "GODKÄNNA", "GODMODIG", "GODMORGON/BRÅVIKEN", "GODMORGON", "GODTA", "GOLIAT", "GÖMMAREN", "GONATT", "GORM", "GOSA HASSEL", "GOSA LILJA", "GOSA PINJE", "GOSA RAPS", "GOSA SLÅN", "GOSA SYREN", "GOSA VÄDD", "GOSIG", "GOTTGÖRA", "GOTTIS", "GOTTLÖSA", "GRÄDDIG", "GRÄDDSÅS", "GRANÅS", "GRANSKÄR", "GRÄSET", "GRÄSMARÖ", "GRATÄNG POTATIS", "GRATINERA", "GRATTIS", "GRÄVA", "GREGOR", "GRENÖ", "GREVBÄCK", "GRILLA", "GRIPANDE", "GROGGY", "GROLAND", "GRÖNPEPPAR", "GRÖNSAKSKAKA", "GRÖNSKA", "GRUNDTAL", "GRUNKA", "GUBBRÖRA", "GULLDIS", "GULLGOSSE", "GULLIRIS", "GULLIVER", "GULLVI", "GULÖRT", "GUNDE", "GUNLIS", "GUNNERN", "GURINE", "GURKA INLAGD", "GURLI", "GUZMANIA", "GYLLEN", "GYNNSAM", "HADSTEN", "HAGALUND", "HÄGGÅS LED", "HÅLLARE", "HÄLLEKNOPP", "HÅLLÖ", "HÄLLVIKEN", "HALOGEN", "HÄLSA", "HALVLOP", "HAMNVIKEN", "HÅMÖ", "HAMPEN", "HÄMTA", "HÄREN", "HARRY", "HÅRTE LED", "HASSELNÖT", "HÄSTVEDA", "HAVBRO", "HAVERDAL", "HEAT", "HEDERLIG", "HEDRA", "HEKTAR", "HELG", "HELMER", "HEMLIG", "HEMMA", "HEMNES", "HEMNES TV", "HEMSJÖ", "HEMSTA", "HENRIKA", "HENRIKSDAL", "HENSVIK", "HERMINE", "HERRUP", "HILDIS", "HILLMARI", "HIMALAYAMIX", "HINNERUP", "HJÄLMAREN", "HJUVIK", "HÖGFÄRDIG", "HÖGSTEN", "HÖGTIDLIG", "HÖJDARE", "HOLMÖ", "HOLMSEL", "HÖNEFOSS", "HOPEN", "HOPPIG", "HOPPLEK", "HÖRJA", "HOVET", "HOVSKÄR", "HUGAD", "HULSIG", "HULTET", "HUMLARE", "HURRIG", "HUSET", "HUSINGE", "HUSÖN", "HUSVIK", "HUTTEN", "HYBY", "HYFSAD", "HYLKJE", "IDEAL", "IDEALISK", "IDEELL", "IDENTISK", "IDOLF", "IDYLLISK", "IKEA", "IKEA PS", "IKEA PS FÅNGST", "IKEA PS FEJÖ", "IKEA PS GULLHOLMEN", "IKEA PS HÅVET", "IKEA PS LÖMSK", "IKEA PS LÖVÅS", "IKEA PS MURBO", "IKEA PS SVINGA", "IKEA STOCKHOLM LED", "INDIRA", "INGAMAJ", "INGATORP/HENRIKSDAL", "INGATORP/INGOLF", "INGATORP/STEFAN", "INGATORP", "INGEBORG", "INGERLISE", "INGO/IVAR", "INGOLF", "INGO", "INNER", "INREDA", "INTEGRAL", "IREVIKEN", "IRIS", "IRJA", "ISALA", "ISDANS", "ISFJORDEN", "ISTAD", "ISUNDA", "IVAR", "JÄBBIG", "JÄLL", "JÄLLVIK", "JÄLSTA", "JÄMKA", "JANSJÖ LED", "JANSJÖ LED USB", "JANSJÖ", "JANUARI", "JÄRA", "JÄRNÖRT", "JÄTTEBRA", "JÄTTELITEN", "JERNVED", "JOKER", "JOKKMOKK", "JÖMNA", "JONISK", "JONOSFÄR", "JONSBO GRYBY", "JONSBO", "JORDET", "JOSEF", "JUBLA", "JULES", "JUSTINA", "KAFFE HELA BÖNOR MÖRKROST", "KAJUTA", "KAKA CHOKLADTRYFFEL", "KAKOR ÄPPLE", "KAKOR CHOKLAD", "KAKOR CHOKLADFLARN", "KAKOR HAVREFLARN", "KAKOR HAVRE", "KAKOR KROKANT", "KALANCHOE", "KALAS", "KALASA", "KALASET", "KALLAX/TJENA", "KALLAX", "KALVÖ", "KALVSJÖN", "KANELSNÄCKA", "KANIST", "KANSLI", "KARDEMUMMA", "KARIT", "KARLABY/KARLSKOGA", "KARLABY/KILLEBERG", "KARLABY", "KÄRLEKEN", "KARLSKOGA", "KARLSKRONA", "KARLSÖ/LÖKÖ", "KARLSÖ", "KARLSTAD", "KÄRRNÄVA", "KARSHOLM", "KASSETT", "KASTANJENÖT", "KATTRUP", "KAVALKAD", "KETCHUP", "KEX", "KILBY", "KILLEBERG", "KILOMETER", "KIVIK", "KLABB", "KLACK", "KLADD PRICKAR", "KLADD RANDIG", "KLADD SMULTRON", "KLÄDE", "KLÄDSAM", "KLAMPEN", "KLASEN", "KLAVIATUR", "KLEMENS", "KLINGSBO", "KLIPPAN", "KLISTRIG", "KLOCKIS", "KLOR LED", "KLÖRUP", "KLÖVSJÖ", "KLÖVSTA", "KLÖXHULT", "KLUDD", "KNÄCKEBRÖD DILL", "KNÄCKEBRÖD FLERKORN", "KNÄCKEBRÖD RÅG", "KNALLA", "KNAPPA", "KNAPPER", "KNAPPSÄV", "KNAPRIG", "KNARRA", "KNARSTA", "KNASTER", "KNIPPE", "KNIPSA", "KNISLINGE", "KNISTA", "KNIVIG", "KNODD", "KNOPPA", "KNOPPARP", "KNORRIG", "KNUBBIG", "KNUFF", "KNYCK", "KÖGE", "KOLDBY", "KOLJA", "KOLON", "KOLSYRAD ÄPPELDRYCK", "KOLSYRAD PÄRONDRYCK", "KOMPLEMENT", "KOMPLEMENT LED", "KONCIS", "KOPPANG", "KOPPAR", "KOPPLA", "KORKEN", "KORNFIBBLA", "KORPO", "KORT", "KORTVARIG", "KÖTTBULLAR", "KOTTEBO", "KRABB", "KRÅKRIS", "KRÅKSKÄR", "KRÄMARE", "KRAMA", "KRAMIG", "KRISTALLER", "KRITTER", "KROBY", "KROKETT", "KROKIG", "KRUSTADER", "KRYDDIG", "KRYSSBO", "KULLADAL", "KULLA", "KULLAR", "KULLEN", "KULLSTA", "KULÖRT", "KUNGSHOLMEN", "KUNGSMYNTA", "KUPOL", "KURA", "KUSINER", "KUVERT", "KVARNÅN", "KVARNÅ", "KVARNVIK", "KVARTÄR", "KVART", "KVIKNE", "KVILL", "KVINTETT", "KVISSLE", "KVITTRA", "KVOT", "KYLIG", "KYLKLAMP", "KYLVÄSKA", "KYLVÄSKA TÅRTA", "LÄBORG", "LÄCKÖ", "LACK", "LADDA", "LAGAN", "LAGG", "LAGRA", "LAGT", "LAIVA", "LAMPAN", "LÄMPLIG", "LANDET", "LÅNGHOLMEN", "LANGÖR", "LÅNGVARIG", "LANSA", "LANTLIV", "LAPPLAND TV", "LAPPLJUNG", "LAPPLJUNG RUTA", "LASAGNE LAX", "LÄSKIG", "LÅTER", "LÅTSAS", "LÄTTAD", "LÄTT", "LAX FILÉ", "LAX GRAVAD", "LAX HELSIDA", "LAX KALLRÖKT FILÉ", "LAX KALLRÖKT", "LAX NAJAD", "LAX VARMRÖKT", "LEDARE LED", "LEDBERG LED", "LEGITIM", "LEIRVIK", "LEKA", "LEKANDE", "LEKARYD LED", "LEKKAMRAT", "LEKMAN", "LEKPLATS", "LEKSVIK", "LEN", "LENDA", "LENHOVDA", "LENNART", "LEN STJÄRNA", "LERDAL", "LERKIL", "LERSTA", "LEVANGER", "LIALOTTA", "LIATORP/HENRIKSDAL", "LIATORP", "LIATORP TV", "LIDAN", "LIKGILTIG", "LIKNANDE", "LIKSIDIG", "LILLABO", "LILLA", "LILLÅNGEN", "LILLARYD", "LILLEPLUTT", "LILLERÖD", "LILLHÖJDEN", "LILLHOLMEN", "LILLIVI", "LILL", "LILLNAGGEN", "LILLÖN", "LIMHAMN", "LINBLOMMA", "LINDMON", "LINDSDAL", "LINDVED", "LINJAL", "LISEL", "LISELOTT", "LITER", "LJUDA", "LJUSA LED", "LJUSÅS UVÅS", "LJUSÅS YSBY", "LJUSNAN", "LJUSNING", "LJUSTERÖ", "LJUST", "LOCK", "LOCKIG", "LOCKSTA", "LÖDDER", "LODRÄT", "LÖJLIG", "LÖKÖ", "LÖNSAM", "LOSJÖN", "LOSSNEN", "LOTS", "LÖVA", "LÖVBACKEN", "LOVLIG", "LUDOVIKA", "LUFSIG", "LUFTIG", "LUGN", "LUGNT", "LUGNVIK", "LUKTNYPON", "LUNDAMO", "LUNDSKÄR", "LUNS", "LUSTIFIK", "LYCKAD", "LYCKOAX", "LYCKSELE HÅVET", "LYCKSELE LÖVÅS", "LYCKSELE MURBO", "LYCKSELE", "LYKTA", "LYNÄS", "LYNDBY", "LYRIK", "LYSING", "LYSTER", "MAFFENS", "MAGASIN", "MAGGA", "MAGNARP", "MAHULT", "MAJKEN", "MAJLIS", "MAJSKORN", "MAJVOR", "MÅLA", "MALÅ", "MÄLARÖ", "MALFORS", "MALIN", "MALINDA", "MALIN FIGUR", "MALIN TRÅD", "MALKOLM", "MALMA", "MALM", "MALOU", "MAMMUT", "MANDAL", "MANDEL", "MÅNLJUS", "MARGARETA", "MARIAM", "MARIEBERG", "MÄRIT", "MARIUS", "MARJUN", "MÄRKLIG", "MARKUS", "MARMORBLAD", "MARSIPAN", "MARTIN", "MARTORP", "MASKROS", "MATA", "MATILDA", "MATRAND", "MÅTTA", "MÅTTFULL", "MÅTTLIG", "MEDVETEN", "MEJLBY", "MELLBY", "MELLTORP/ADDE", "MELLTORP/MARIUS", "MELLTORP/NISSE", "MELLTORP/REIDAR", "MELLTORP", "MELODI", "MERETE", "METRIK", "MICKE", "MILDRA", "MINDE", "MINIBJÖRN", "MINNA", "MINNEN", "MINUT", "MIXTUR", "MJÖD", "MJUKNÄVA", "MÖBORG", "MOGEN", "MOHEDA", "MOLGER", "MONGSTAD", "MÖNSTRAD", "MONTERA", "MORGEDAL", "MORGONGÅVA", "MÖRKT", "MORTORP", "MORUM", "MORVIK", "MOSHULT", "MOSJÖ TV", "MOSSEN", "MOTORP", "MULA", "MULIG", "MURKLA", "MUSIK", "MUSKÖ", "MUSKOTNÖT", "MYDAL", "MYGGA", "MYKEN", "MYNDIG", "MYRBACKA", "MYSA GRÄS", "MYSA RÖNN", "MYSA ROSENGLIM", "MYSA STRÅ", "MYSA VETE", "MYSIG", "MYSINGSÖ", "MYSKMÅRA", "NÄCKTEN", "NANDOR", "NANIG", "NÄPEN", "NÄSSJÖ", "NÄSUM", "NATTLIG", "NATURKÄR", "NÄVVIVA", "NEDDA", "NEGLINGE", "NEKTARIN", "NESNA", "NIDELVA", "NILS", "NINNI FIGUR", "NINNI RUND", "NINNI TRÅD", "NISSE", "NITTORP TV", "NIVÅ", "NJUTA", "NOCKEBY", "NÖDVÄNDIG", "NOJSIG", "NOLBYN", "NOLMYRA", "NOMINELL", "NON", "NON LED", "NORBERG/NISSE", "NORBERG", "NORBO", "NORDDAL", "NORDEN/FRODE", "NORDEN/IDOLF", "NORDEN/NORRNÄS", "NORDEN/TERJE", "NORDEN/VILMAR", "NORDEN", "NORDLI", "NORNA", "NORRLIDA", "NORRNÄS", "NOT", "NOTUDDEN", "NUMERÄR", "NUTID", "NYFORS", "NYMÖ", "NYPONROS", "NYTTIG", "NYTTIG WFL", "NYTTJA", "NYVAKEN", "NYVOLL", "OANVÄND", "OBEROENDE", "OCKSÅ", "ODDA", "ODENSVIK", "OERSÄTTLIG", "OFELIA BLAD", "OFELIA", "OFELIA VASS", "OFFENTLIG", "OFTA", "OLEBY", "OLIK", "OLLSTA", "OLOFSTORP", "OLSKÄR", "OLTEDAL", "OLUNDA", "OMAR", "OMÄTTLIG", "OMBYTLIG", "OMFATTANDE", "OMSORG", "OMTYCKT", "OMVÄXLANDE", "ONSJÖ LED", "OPTIMAL", "ORÄDD", "ORDENTLIG", "ORDNA", "ORDNING", "ORE", "ORGEL", "ORMKAKTUS", "ORNÄS", "ORRBERG", "ORREVIK", "ORRNÄS", "OST BLÅMÖGEL", "OSTED", "OST", "OST HUSHÅLLSOST", "OSTRON", "OTTAVA", "OTTIL", "ÖDESTRÄD", "ÖPPEN", "ÖRKENED", "ÖRSTED", "ÖSTANÅ", "ÖSTERSLÖV", "ÖSTLIG", "ÖVERENS", "ÖVRABY", "ÖVRE", "PÅBÖRJA", "PACHIRA AQUATICA", "PAJ RABARBER", "PALMLILJA", "PANNÅ", "PANNKAKOR", "PAPAJA", "PARANÖT", "PÄRLVIVA", "PASTEJ KRABBA", "PASTEJ LAX", "PATRIK", "PATRULL", "PAX", "PELLO", "PENNINGBLAD", "PEPPARKAKA CITRUS", "PEPPARKAKA", "PEPPARKAKA MANDEL", "PEPPARKAKOR", "PHALAENOPSIS", "PIZZABITAR", "PJÄS", "PJÄTTERYD", "PLACERA", "PLAN", "PLASTIS", "PLATS", "PLUFSIG", "PLUGGIS", "POÄNG", "POKAL", "POLARVIDE", "POMP", "PORTIS", "POTATISCHIPS GRÄDDFIL", "POTATISCHIPS SALTADE", "POTATISMOS", "POTATIS", "PRÄGEL", "PRAKTFULL", "PREBEN", "PREMIÄR", "PRESSA", "PRICKIG", "PRIMITIV", "PRINSKORV", "PRODUKT", "PRÖJS", "PROMENAD", "PROPPMÄTT", "PRUTA", "PUGG", "PULT", "PYNTA", "PYSSLA", "PYSSLINGAR", "RABALDER", "RÄCKA/HUGAD", "RÄCKA", "RÅDIG", "RAFFIG", "RÅGKORN", "RAGNBORG", "RÅGRUND", "RAJTAN", "RÄKOR MED SKAL", "RÄKOR UTAN SKAL", "RAMSÄTRA", "RAMSÄTRA TV", "RAMSKÄR", "RAMSÖ", "RAMSTA", "RANARP", "RÄNDER", "RANDIG", "RANDLEV", "RÄPPE", "RÅSKOG", "RAST", "RÄTA", "RATIONELL", "RATIONELL LED", "RÄTTVIKEN", "RÄTTVIK", "RAVENEA", "REDA", "REGOLIT", "REIDAR", "REKARNE", "REKTANGEL", "RENATE", "RENLIG", "RENS", "RESELE", "RESÖ", "RETRÄTT", "RETSAM", "RETUR", "RIBBA LED", "RIBBA", "RIFFLA", "RIGGA", "RIKLIG", "RIKTIG", "RILL", "RINGSJÖN", "RINGSKÄR", "RISKORN", "RISÖ", "RISÖR", "RITVA", "RODD", "ROKNÄS", "ROMANTISK", "RÖNNSKÄR", "RÖRHOLT", "RÖRSKÄR", "RÖRT", "ROSENDUN", "ROSÉPEPPAR", "ROSMARIE", "ROSTAD LÖK", "RÖSTI", "ROTERA", "ROXÖ", "RUMMET", "RUNDLIG", "RUNNEN", "RUNSKÄR", "RUSCH", "RUSTIK", "RUTBO", "RUTER", "RUTIN", "RYMDBAS", "RYMDEN LED", "RYMLIG", "SAFT BLÅBÄR", "SAFT FLÄDER", "SAFT LINGON", "SAFT RABARBER", "SAGODRAKE", "SAGOSTEN", "SÄLLSYNT", "SALMBÄR", "SALMI/TOBIAS", "SALMI", "SALONG", "SALTGRUND", "SALTIG", "SAMLA", "SAMSÖ", "SAMSPELT", "SAMTID", "SANDIG", "SANELA", "SÄNGDAGS", "SÅNGEN", "SÅNGTRAST", "SANSAD", "SÄRÖ", "SÅS CITRON", "SÅS PEPPARROT", "SÅS SENAP", "SÅS TOMAT", "SÅS VANILJ", "SATSNING", "SÄTTA", "SÄVERN", "SAXNÄS", "SAXSKÄR", "SCHOTTIS", "SEDLIG", "SEGLARÖ", "SEKIN", "SEKOND", "SELJE", "SEMINE", "SEMVIK", "SENAP GROV", "SENAP MILD", "SENIOR", "SENSUELL", "SICKAN", "SIGNE", "SIGNUM", "SIGURD", "SILL DILL", "SILL GRÄDDFIL", "SILL INLAGD", "SILL LÖK", "SILL MATJES", "SILLROM", "SILL SENAP", "SILL SOMMAR", "SILL VITLÖK", "SILVÅKRA", "SILVERÅN", "SINDAL", "SINGLA", "SKÄCK", "SKÅDA", "SKÄNKA", "SKARPÖ", "SKARPSILL", "SKÅRUP", "SKAVGRÄS", "SKEBY", "SKIMMER", "SKOGABY", "SKOGHALL", "SKOGN", "SKOJA", "SKOJIG", "SKOJ", "SKÖNHET", "SKORPOR FULLKORN", "SKORPOR KARDEMUMMA", "SKÖTSAM", "SKÖTSEL", "SKOVEL", "SKRIBENT", "SKRUVSTA", "SKUBB", "SKULPTUR", "SKURAR", "SKYDDA", "SKYDD", "SKYLTA", "SKYN", "SLÄT", "SLÄTTEN", "SLÄTTHULT", "SLIPAD", "SLITBAR", "SLUGGER", "SLUKA", "SLUMRA", "SMÅBORRE", "SMÄCKER", "SMÅGLI", "SMAKA", "SMÅKRYP", "SMÅNATE", "SMARTA", "SMÄRT", "SMASKA", "SMÅSLUG", "SMILA BAGGE", "SMILA BLOMMA", "SMILA HJÄRTA", "SMILA MÅNE", "SMILA SOL", "SMILA STJÄRNA", "SMÖRBOLL", "SMÖRGÅSKAVIAR", "SMULA", "SMYCKA", "SMYCKE", "SMYG", "SNABBVINGE", "SNÅR", "SNÄRTIG", "SNIGLAR", "SNIKA", "SNILLE", "SNITSIG", "SNITTA", "SNÖIG", "SNUDDA", "SOARÉ", "SOCKERÄRT", "SOCKER", "SOCKERKAKA", "SODA", "SÖDERHAMN", "SÖDER", "SOFIA", "SÖFTEN", "SOLFINT", "SOLIG", "SOLIGT", "SOLKUL", "SOLMYRA", "SOLMYS", "SOLRUN", "SOLSTA", "SOLUR", "SOLVINDEN", "SOMMARFINT", "SÖMNIG", "SOMRIG", "SÖNDRUM", "SONGE", "SÖRE", "SORTERA", "SÖTSAK DAMMSUGARE", "SÖTSAK KAKAOBOLL", "SÖTSAK SKUMTOPP", "SPÅNA", "SPARKA", "SPÄRRA", "SPATHIPHYLLUM", "SPECIELL", "SPELPLAN", "SPEXA", "SPINNA", "SPIRITUELL", "SPÖKA LED", "SPONTAN", "SPRIDA LED", "SPRITTA", "STABBIG", "STABIL", "STÄDJAN", "STÄLL", "STÄM", "STAVE", "STEFAN", "STEK", "STENKLÖVER", "STENSTORP", "STIG", "STINN", "STOCKHOLM", "STOLJAN", "STOLMEN", "STOPP", "STOPP FILT", "STORÅ", "STORJORM", "STORNÄS/HENRIKSDAL", "STORNÄS", "STORSELE", "STRÅLA", "STRÅLANDE", "STRANDMON", "STRANDVETE", "STRANNE LED", "STRAPATS", "STRIBERG LED", "STRIND", "STRÖMBY", "STROSA", "STRÖVA", "STUGVIK", "STUVA", "SUCCULENT", "SULTAN ALSARP", "SULTAN ÅRAM", "SULTAN ATLÖY", "SULTAN ATNA", "SULTAN", "SULTAN HALLEN", "SULTAN HANESTAD", "SULTAN HANSBO", "SULTAN HAVBERG", "SULTAN HEGGEDAL", "SULTAN HOGLA", "SULTAN HOLMSTA", "SULTAN HULTSVIK", "SULTAN HURVA", "SULTAN LADE", "SULTAN LAXEBY", "SULTAN LURÖY", "SULTAN TAFJORD", "SULTAN TJÖME", "SULTAN TORÖD", "SUMMELN", "SUMMERA", "SUNDERÖ", "SUNDSVIK", "SUNDVIK", "SUNNAN LED", "SUNRID", "SUTARE", "SVAJS", "SVALEN", "SVALKA", "SVÄRTA", "SVARTÅSEN", "SVEIO", "SVELVIK", "SVENSBY", "SY", "SYDLIG", "SYLT APELSIN", "SYLT HALLON", "SYLT HJORTRON", "SYLT JORDGUBB", "SYNAS LED", "SYRLIG", "TAG", "TÄLLEVIKEN", "TALLÖRT", "TÄNDA", "TÅNGKORN", "TÄRENDÖ/ADDE", "TÄRENDÖ/GUNDE", "TÄRENDÖ", "TÄRNA", "TÄRNAN", "TÅRNBY", "TÄRNÖ", "TÅRTA BLÅBÄR", "TÅRTA CHOKLADKROKANT", "TÅRTA MANDEL", "TÅRTA MÖRK CHOKLAD", "TARVA", "TÅSINGE", "TÅSTRUP", "TECKEN", "TECKNAT", "TEJN", "TEKLA", "TERESIA", "TERJE", "TERMOSFÄR", "TERTIAL", "TICKAR", "TIDAFORS", "TIDIG", "TIDNY", "TIDSENLIG", "TILLANDSIA CYANEA", "TILLBAKA", "TILLTALA", "TIMGLAS", "TINDRA", "TISDAG", "TITTA DJUR", "TIVED LED", "TJÄREBY", "TJUSIG", "TOBIAS", "TOFSVIVA", "TOFTBO", "TOFTERYD", "TOFTERYD TV", "TOGA", "TOKIG", "TOLERANT", "TOLSBY", "TOMAT", "TORBJÖRN", "TORKA", "TORKAD", "TORKEL", "TORKIS", "TORNA", "TORSBY/BERNHARD", "TORSBY/ERLAND", "TORSBY/MARTIN", "TORSBY/TOBIAS", "TORSBY/VILMAR", "TORSBY", "TORVA", "TRÅDKLÖVER", "TRÅDTÅG", "TRÅL", "TRAMPA", "TRANETORP/ESBJÖRN", "TRANETORP", "TRÄNING", "TRATT", "TRENDIG", "TRENSUM", "TRILLING", "TRIPP", "TRIVSAM", "TROFAST", "TROGEN", "TROGSTA", "TROJKA", "TROLSK", "TROMSÖ", "TRONES", "TROPISK", "TROSS", "TROSSÖ", "TROVÄRDIG", "TRYGG", "TRYSIL", "TUDI", "TULLIA", "TULLSTA", "TUNDRA", "TUPPLUR", "TURBO", "TUSENSKÖNA", "TUTIG", "TUVE", "TVILLING", "TVINGEN", "TVIS", "TYDA", "TYDINGEN", "TYSNES", "UDDGRUND", "ULLAMAJ", "ULLASTINA", "ULLGUMP", "ULLKAKTUS", "ULSBERG", "ULVÖN", "ULVSBO", "UMFORS", "UNDIS", "UNGDOM", "UNG DRILL", "UPPBO", "UPPENBAR", "UPPHETTA", "UPPLÄGG", "UPPTÄCKA", "UPPVISA", "URBAN", "URSULA", "UTBY", "UTELEK", "UTFÖRA", "UTRUSTA", "UTSIRA", "UTTER", "VACKERT", "VÄCKIS", "VÄGGIS", "VÅGRÄT", "VAKEN", "VALBY RUTA", "VÄLKÄND", "VANADIN", "VANDRING", "VANJA", "VÄNLIG", "VÄNNERNA", "VARAKTIG", "VÅRDA", "VÄRDE", "VARDÖ", "VÅRGYLLEN", "VARIERA", "VARLIG", "VÄRMDÖ", "VARMLUFT", "VARNHEM", "VARPAN", "VÅRSKÖNA", "VÄSENTLIG", "VASEN", "VÄSTER LED", "VÄTE", "VATTENTÄT", "VATTNA", "VEJMON", "VEMB", "VESSLA", "VETTRE", "VIDJA", "VIFT", "VIGDIS", "VIKIS", "VIKT LED", "VILBORG", "VILGOT/NOMINELL", "VILGOT", "VILLIG", "VILMAR", "VILSHULT", "VINÄGER", "VINNA", "VINRANKA", "VIPPMÅLLA", "VIRRE", "VIRRING", "VIRSERUM", "VISKA", "VISSLA", "VITAMINER", "VITFJÄRIL", "VITLING", "VITTEN", "VITTSJÖ", "VITTSJÖ TV", "VIVAN", "VOLMAR", "VOLYM", "VRETA", "VURM", "VYSSA", "WERNA", "YDBY"
];

let state = new GameState(words[Math.floor(Math.random() * words.length)]);
state.displayWord();
